* My emacs journey

To install, run the following and restart your Emacs

#+BEGIN_SRC 
git clone git@github.com:lzhoucs/.emacs.d.git ~/.emacs.d
#+END_SRC

This mono-repo contains the following emacs distributions
  - spacemacs - spacemacs repo
  - doomemacs - doomemacs repo
  - emacs - my emacs repo

This repo also contains an entry file ~init.el~ which serves as a loader to one of the emacs distributions above

* doomemacs instructions
** doomemacs fresh install
  - clone repo into <current-dir>/distributions/doomemacs
  - make sure ~doomemacs/bin~ is in the path: ~export PATH="$PATH:$HOME/.emacs.d/distributions/doomemacs/bin"~
  - make sure ~DOOMDIR~ is set: ~export ~/.emacs.d/distribution-configs/DOOMDIR~ 
  - switch to doomemacs in the loader
  - turnoff emacs
  - run ~doom install~ in the command line
  - start emacs
** doomemacs update
  - pull latest from repo <current-dir>/distributions/doomemacs
  - make sure ~doomemacs/bin~ is in the path: ~export PATH="$PATH:$HOME/.emacs.d/distributions/doomemacs/bin"~
  - make sure ~DOOMDIR~ is set: ~export ~/.emacs.d/distribution-configs/DOOMDIR~ 
  - switch to doomemacs in the loader
  - turnoff emacs
  - run the following in the command line. See [[https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#update--rollback][docs on update]]
    #+BEGIN_SRC sh
doom clean      # Ensure your config isn't byte-compiled
doom sync       # synchronizes your config with Doom Emacs. This includes add new packages, remove unused packages, but not include updating existing packages
# no longer available
# doom update     # updates installed packages
    #+END_SRC
  - start emacs
** other notes
doomemacs rely on external ~emacs~ command to be available in ~PATH~ before
install/refresh can work properly. This makes it tricky to switch emacs
versions or simply use macOS native Emacs.app where a ~emacs~ command is simply not in
the ~PATH~. With all other emacs distributions such as spacemacs, such a problem
doesn't exist since what we use is what it use. See https://github.com/hlissner/doom-emacs/issues/71 on how to change emacs command.
* spacemacs instructions
** spacemacs fresh install
  - clone repo into <current-dir>/distributions/spacemacs
  - make sure ~SPACEMACSDIR~ is set: ~export SPACEMACSDIR=~/.emacs.d/distribution-configs/SPACEMACSDIR~
    See: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#alternative-dotdirectory
  - switch to spacemacs in the loader
  - turnoff emacs
  - start emacs
** spacemacs update
  - pull latest from repo <current-dir>/distributions/spacemacs
  - make sure ~SPACEMACSDIR~ is set: ~export SPACEMACSDIR=~/.emacs.d/distribution-configs/SPACEMACSDIR~
  - switch to spacemacs in the loader
  - turnoff emacs
  - start emacs
  - run ~SPC f e D~ to compare with latest template config and manually merge

* doomemacs TODO List
** org-super-agenda
https://www.youtube.com/watch?v=hZpDdbflt8c
* TODO List
** TODO Auto delete packages defined by ~use-package~
** TODO stylus file indentation and syntax highlight
** TODO TypeScript syntax highlight
